name: Run tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v4

        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: '18'
        
        - name: Install and Build
          run: |
            npm install
            npm install -g typescript
            tsc

        - name: Start server
          run: |
            node . &
            echo $! > server.pid
        
        - name: Run tests
          run: |
            npx wait-on http://localhost:2773
            npx jest

        - name: Kill server
          run: kill $(cat server.pid)
